name: 'Publich Gitbook'
description: 'Publish Gitbook to GitHub Pages'
author: 'Liren Tu'
branding:
  icon: 'book'
  color: 'blue'
inputs:
  github_token:
    description: 'Github token for the repo.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
