name: 'Publish Gitbook'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publich Gitbook
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
